--ALTER USER webdb IDENTIFIED BY 1234;

--AUTHOR TABLE CREATE
CREATE TABLE AUTHOR(
	AUTHOR_ID		NUMBER(10),
	AUTHOR_NAME		VARCHAR(100)	NOT NULL,
	AUTHOR_DESC		VARCHAR2(500),
	PRIMARY KEY(AUTHOR_ID)
)

--BOOK TABLE CREATE
CREATE TABLE BOOK(
	BOOK_ID		NUMBER(10),
	TITLE		VARCHAR2(100) NOT NULL,
	PUBS		VARCHAR2(100),
	PUB_DATE	DATE,	
	AUTHOR_ID	NUMBER(10),	
	PRIMARY KEY(BOOK_ID),  --BOOK_ID를 PRIMARY KEY로 제약
	CONSTRAINT C_BOOK_FK FOREIGN KEY (AUTHOR_ID)  --AUTHOR_ID 컬럼은 외래키로 지정
	REFERENCES AUTHOR (AUTHOR_ID)  --외래키인 AUTHOR_ID 컬럼의 출처는 AUTHOR 테이블
)

--DROP TABLE
DROP TABLE BOOK
DROP TABLE AUTHOR

--INSERT DATA TO AUTHOR TABLE
INSERT INTO AUTHOR(AUTHOR_ID,AUTHOR_NAME)
VALUES(2,'이문열')
INSERT INTO AUTHOR
VALUES (1, '박경리', '토지 작가')

--UPDATE DATA TO AUTHOR TABLE
UPDATE AUTHOR
SET	AUTHOR_NAME = '기안84',
	AUTHOR_DESC = '웹툰작가, 태어난김에 세계일주'
WHERE AUTHOR_ID = 1

--DELETE ROW FROM TABLE
DELETE FROM AUTHOR 
WHERE AUTHOR_ID = 1

--CREATE SEQUENCE FOR COUNT VALUES
CREATE SEQUENCE SEQ_AUTHOR_ID
INCREMENT BY 1
START WITH 1
CREATE SEQUENCE SEQ_BOOK_ID
INCREMENT BY 1
START WITH 1
--AND INSERT TO TABLE
INSERT INTO AUTHOR 
VALUES(SEQ_AUTHOR_ID.NEXTVAL, '박경리', '토지 작가')
INSERT INTO AUTHOR
VALUES(SEQ_AUTHOR_ID.NEXTVAL, '이문열', '삼국지 작가')

INSERT INTO AUTHOR 
VALUES(SEQ_AUTHOR_ID.NEXTVAL,'이문열','경북 영양')
INSERT INTO AUTHOR 
VALUES(SEQ_AUTHOR_ID.NEXTVAL,'박경리','경상남도 통영')
INSERT INTO AUTHOR 
VALUES(SEQ_AUTHOR_ID.NEXTVAL,'유시민','17대 국회의원')
INSERT INTO AUTHOR 
VALUES(SEQ_AUTHOR_ID.NEXTVAL,'기안84','기안동에서 산 84')
INSERT INTO AUTHOR 
VALUES(SEQ_AUTHOR_ID.NEXTVAL,'강풀','온라인 만화가')
INSERT INTO AUTHOR 
VALUES(SEQ_AUTHOR_ID.NEXTVAL,'김영하','알쓸신잡')


INSERT INTO BOOK 
VALUES(SEQ_BOOK_ID.NEXTVAL,'우리들의 일그러진 영웅','다림','1998-02-22',1)
INSERT INTO BOOK 
VALUES(SEQ_BOOK_ID.NEXTVAL,'삼국지','민음사','2002-03-01',1)
INSERT INTO BOOK 
VALUES(SEQ_BOOK_ID.NEXTVAL,'토지','마로니에북스','2012-08-15',2)
INSERT INTO BOOK 
VALUES(SEQ_BOOK_ID.NEXTVAL,'유시민의 글쓰기 특강','생각의길','2015-04-01',3)
INSERT INTO BOOK 
VALUES(SEQ_BOOK_ID.NEXTVAL,'패션왕','중앙북스(books)','2012-02-22',4)
INSERT INTO BOOK 
VALUES(SEQ_BOOK_ID.NEXTVAL,'순정만화','재미주의','2011-08-03',5)
INSERT INTO BOOK 
VALUES(SEQ_BOOK_ID.NEXTVAL,'오직두사람','문학동네','2017-05-04',6)
INSERT INTO BOOK 
VALUES(SEQ_BOOK_ID.NEXTVAL,'26년','재미주의','2012-02-04',5)

--강풀 DESC 서울특별시로 변경
UPDATE AUTHOR 
SET AUTHOR_DESC = '서울특별시'
WHERE AUTHOR_NAME = '강풀'

--AUTHOR 테이블에서 기안84 데이터 삭제
DELETE FROM AUTHOR 
WHERE AUTHOR_NAME = '기안84'


SELECT SEQ_AUTHOR_ID.NEXTVAL FROM DUAL  --다음 시퀀스
SELECT SEQ_AUTHOR_ID.CURRVAL FROM DUAL 	--현재 시퀀스
SELECT SEQ_BOOK_ID.NEXTVAL FROM DUAL
SELECT SEQ_BOOK_ID.CURRVAL FROM DUAL
DROP SEQUENCE SEQ_AUTHOR_ID --시퀀스 제거
DROP SEQUENCE SEQ_BOOK_ID	--시퀀스 제거

--SELECT
SELECT * FROM BOOK

SELECT * FROM AUTHOR
ORDER BY AUTHOR_ID ASC

SELECT B.BOOK_ID,
	   B.TITLE ,
	   B.PUBS,
	   B.PUB_DATE ,
	   A.AUTHOR_ID ,
	   A.AUTHOR_NAME,
	   A.AUTHOR_DESC
FROM BOOK B, AUTHOR A
WHERE B.AUTHOR_ID = A.AUTHOR_ID
